### ISSUE TITLE
[Bug]: NotableBubbleText does not work with any Geckolib mobs.

### ISSUE THREAD

**Issue by neilwightman** [Mrbysco/NotableBubbleText#2]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

47.0.35

### Minecraft version

1.20.1

### Mod version

1.0.1

### Java version

java "17.0.1" 2021-10-19 LTS

### Issue Description

Geckolib is currently incompatible with NotableBubbleText .   Geckolib doesnt use fire a RenderLivingEvent.Post event as it never has a EntityModel.
Geckolib has a GeoRenderEvent.Entity.Post which is fired after the rendering has complete.
Geckolib can't just create some fake EntityModel.

Below is a method which fixes this issue but I dont know enough about dynamically loading code if Geckolib is there or not to make a pull request which doesnt break without Geckolib.

ClientHandler insert : 

```java
    @SubscribeEvent
    public  <T extends LivingEntity> void onGeckoEntityRender(GeoRenderEvent.Entity.Post event) {
        // Copied from https://github.com/Mrbysco/NotableBubbleText
        final Minecraft mc = Minecraft.getInstance();
        final Player localPlayer = mc.player;
        if (localPlayer == null) return;

        Entity entity = event.getEntity();
        if (entity instanceof LivingEntity){
            final LivingEntity livingEntity = (LivingEntity) entity;
            if (livingEntity.isInvisibleTo(localPlayer)) return;

            String author = BubbleHandler.getAuthor(livingEntity.getUUID());
            if (!author.isEmpty()) {
                List<BubbleText> bubbles = BubbleHandler.getBubbles(author);
                if (bubbles.isEmpty()) return;
                BubbleText bubble = bubbles.get(0);

                final Level level = mc.level;
                if (level == null) return;
                final long currentTime = level.getGameTime();

                long bubbleTime = bubbles.size() > 1 ? 50 : 200;
                long bubbleAge = bubble.getAge(currentTime);
                float bubbleAlpha = bubble.getAlpha(currentTime);

                final Font font = mc.font;
                final PoseStack poseStack = event.getPoseStack();
                final EntityDimensions dimensions = livingEntity.getDimensions(livingEntity.getPose());
                final MultiBufferSource multiBufferSource = event.getBufferSource();
                final EntityRenderDispatcher renderDispatcher = mc.getEntityRenderDispatcher();
                final double nameOffset = getNameOffset(renderDispatcher, livingEntity);

                BubbleRenderer.renderBubbleText(bubble, poseStack, font, multiBufferSource, renderDispatcher,
                        dimensions.height, bubbleAlpha, event.getPackedLight(), nameOffset);

                if (bubbleAge > bubbleTime) {
                    BubbleHandler.removeBubble(bubble);
                }
            }
        }
    }
```

**Comment by neilwightman** [comment]
I was using     
implementation fg.deobf('software.bernie.geckolib:geckolib-forge-1.20:4.2')

**Comment by Mrbysco** [comment]
Will add support shortly, thanks for reporting

**Comment by neilwightman** [comment]
Thanks.  That's great.
