### ISSUE TITLE
[Suggestion]: Compatibility with Beautified Chat

### ISSUE THREAD

**Issue by QwertRvg** [Mrbysco/NotableBubbleText#3]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

The mod beautified chat changes the appearance of the chat. I, for instance, have it set so that send time and username are displayed before the message.
Like so:
![image](https://github.com/Mrbysco/NotableBubbleText/assets/89683173/86c1bc86-f328-4912-a606-644f1e469ef1)

This does show up in the speech bubble though, which isn't that great.
The speech bubble is only visible to nearby players and is used more for a "direct conversation" if that makes sense.
So having these infos about the time and name are unnecessary here.

Is there a way to remove it?

**Comment by Mrbysco** [comment]
A new build is being built and uploaded that should fix compat

**Comment by QwertRvg** [comment]
Thank you so much!

**Comment by Mrbysco** [comment]
I've tested with Beautified Chat myself but if you could double check :)

**Comment by QwertRvg** [comment]
It works! It's perfect! Thanks so much!
