### ISSUE TITLE
[Suggestion]: Backport 1.20.x changes to 1.19.2 forge

### ISSUE THREAD

**Issue by QianFuv** [Mrbysco/NotableBubbleText#4]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

The changes in 1.20.x, particularly the option to hide player names, are very important. Is it possible to port these excellent improvements to 1.19.2?

**Comment by Mrbysco** [comment]
Done, version should be available shortly
